# Generated by Django 2.1.2 on 2018-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Vacation', 'Vacation'), ('Sick Leave', 'Sick Leave')], max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave_limit', models.IntegerField()),
                ('vacations_limit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
