# Generated by Django 2.1.2 on 2018-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_request_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='reason',
            new_name='request_status',
        ),
        migrations.AddField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('Vacation', 'Vacation'), ('Sick Leave', 'Sick Leave')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
