# Generated by Django 2.1.2 on 2018-11-22 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20181122_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='office.Profile'),
            preserve_default=False,
        ),
    ]
