# Generated by Django 2.1.2 on 2018-11-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0005_request_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
