# Generated by Django 2.1.2 on 2018-10-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
