# Generated by Django 2.1.2 on 2018-11-22 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20181111_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 22, 12, 24, 12, 128249)),
        ),
    ]
