# Generated by Django 2.1.2 on 2018-11-22 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20181122_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 22, 13, 0, 58, 335308)),
        ),
    ]
