# Generated by Django 2.1.2 on 2018-11-22 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20181122_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 11, 22, 17, 5, 36, 966333)),
        ),
    ]
